"""add court type column

Revision ID: a5812fc8c196
Revises: 
Create Date: 2024-01-31 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5812fc8c196'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Add court_type column to tennis_courts table
    op.add_column('tennis_courts', sa.Column('court_type', sa.String(50)), schema='dwh')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('court_availability', 'last_updated',
               existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               schema='dwh')
    op.alter_column('file_registry', 'load_timestamp',
               existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               schema='raw_files')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_registry', 'load_timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               schema='raw_files')
    op.alter_column('court_availability', 'last_updated',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               schema='dwh')
    # ### end Alembic commands ###
    
    # Drop court_type column from tennis_courts table
    op.drop_column('tennis_courts', 'court_type', schema='dwh')
